<?php 

$mod_strings = array ( 
  'LBL_TEAM' => 'Team', 
  'LBL_TEAMS' => 'Teams', 
  'LBL_TEAM_ID' => 'Team Id', 
  'LBL_ASSIGNED_TO_ID' => 'Assigned User Id', 
  'LBL_ASSIGNED_TO_NAME' => 'Assigned to', 
  'LBL_ID' => 'ID', 
  'LBL_DATE_ENTERED' => 'Date Created', 
  'LBL_DATE_MODIFIED' => 'Date Modified', 
  'LBL_MODIFIED' => 'Modified By', 
  'LBL_MODIFIED_ID' => 'Modified By Id', 
  'LBL_MODIFIED_NAME' => 'Modified By Name', 
  'LBL_CREATED' => 'Created By', 
  'LBL_CREATED_ID' => 'Created By Id', 
  'LBL_DESCRIPTION' => 'Description', 
  'LBL_DELETED' => 'Deleted', 
  'LBL_NAME' => 'Part Name', 
  'LBL_CREATED_USER' => 'Created by User', 
  'LBL_MODIFIED_USER' => 'Modified by User', 
  'LBL_LIST_FORM_TITLE' => 'Parts List', 
  'LBL_MODULE_NAME' => 'Parts', 
  'LBL_MODULE_TITLE' => 'Parts', 
  'LBL_HOMEPAGE_TITLE' => 'My Parts', 
  'LNK_NEW_RECORD' => 'Create Parts', 
  'LNK_LIST' => 'Parts', 
  'LBL_SEARCH_FORM_TITLE' => 'Search Parts', 
  'LBL_HISTORY_SUBPANEL_TITLE' => 'View History', 
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Activities', 
  'LBL_TEST_PARTS_SUBPANEL_TITLE' => 'Parts', 
  'LBL_NEW_FORM_TITLE' => 'New Parts', 
  'LBL_PART_REFERENCE_NUMBER' => 'Part Reference Number', 
  'LBL_PART_LOCATION' => 'Part Location', 
  'LBL_VIEWPARTIMAGE' => 'View Part Image', 
  'LBL_VIEWPARTIMAGE_TITLE' => 'View Part Image [Alt+P]', 
  'LBL_VIEWPARTIMAGE_BUTTON_KEY' => 'P', 
); 
